<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class AppointmentResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        if(count($this->items) == 10){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            'service' => new ServiceResource($this->items[2]->service),
            'service' => new ServiceResource($this->items[3]->service),
            'service' => new ServiceResource($this->items[4]->service),
            'service' => new ServiceResource($this->items[5]->service),
            'service' => new ServiceResource($this->items[6]->service),
            'service' => new ServiceResource($this->items[7]->service),
            'service' => new ServiceResource($this->items[8]->service),
            'service' => new ServiceResource($this->items[9]->service),
            ];
        }elseif(count($this->items) == 9){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            'service' => new ServiceResource($this->items[2]->service),
            'service' => new ServiceResource($this->items[3]->service),
            'service' => new ServiceResource($this->items[4]->service),
            'service' => new ServiceResource($this->items[5]->service),
            'service' => new ServiceResource($this->items[6]->service),
            'service' => new ServiceResource($this->items[7]->service),
            'service' => new ServiceResource($this->items[8]->service),
            ];
        }elseif(count($this->items) == 8){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            'service' => new ServiceResource($this->items[2]->service),
            'service' => new ServiceResource($this->items[3]->service),
            'service' => new ServiceResource($this->items[4]->service),
            'service' => new ServiceResource($this->items[5]->service),
            'service' => new ServiceResource($this->items[6]->service),
            'service' => new ServiceResource($this->items[7]->service),
            ];
        }elseif(count($this->items) == 7){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            'service' => new ServiceResource($this->items[2]->service),
            'service' => new ServiceResource($this->items[3]->service),
            'service' => new ServiceResource($this->items[4]->service),
            'service' => new ServiceResource($this->items[5]->service),
            'service' => new ServiceResource($this->items[6]->service),
            ];
        }elseif(count($this->items) == 6){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            'service' => new ServiceResource($this->items[2]->service),
            'service' => new ServiceResource($this->items[3]->service),
            'service' => new ServiceResource($this->items[4]->service),
            'service' => new ServiceResource($this->items[5]->service),
            ];
        }elseif(count($this->items) == 5){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            'service' => new ServiceResource($this->items[2]->service),
            'service' => new ServiceResource($this->items[3]->service),
            'service' => new ServiceResource($this->items[4]->service),
            ];
        }elseif(count($this->items) == 4){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            'service' => new ServiceResource($this->items[2]->service),
            'service' => new ServiceResource($this->items[3]->service),
            ];
        }elseif(count($this->items) == 3){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            'service' => new ServiceResource($this->items[2]->service),
            ];
        }elseif(count($this->items) == 2){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            'service' => new ServiceResource($this->items[1]->service),
            ];
        }elseif(count($this->items) == 1){
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items,
            'service' => new ServiceResource($this->items[0]->service),
            ];
        }else{
            return [
            'id' => $this->id,
            'client_id' => $this->client_id,
            'client' => $this->client->user,
            'client' => new ClientResource($this->client),
            'pet_id' => $this->pet_id,
            'pet' => $this->pet,
            'breed_id' => $this->pet->breed_id,
            'breed' => new BreedResource($this->pet->breed),
            'vehicle_id' => $this->vehicle_id,
            'vehicle_assign' => $this->vehicle_assign,
            'assign_vehicle' => $this->assign_vehicle,
            'vehicle' => $this->vehicle,
            'time' => $this->time,
            'date' => date('d/m/Y',strtotime($this->date)),
            'date_simple' => $this->date,
            'total_cost' => $this->total_cost,
            'status' => $this->status,
            'items' => $this->items
            ];
        }
    }
}
